// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Infrastructure.Data;

#nullable disable

namespace MyApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MyApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 3, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@test.com",
                            PasswordHash = "AQAAAAIAAYagAAAAELqKiy3aTopPm6hxrTuuGjL/94HrJp2z10/RP85PdOh8AxEHIDiB4V1rAwh30T2Hnw==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 3, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@test.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEMG2RQMUT2Y271SAT61FoEtW/c9klI8kUSq9NZrL9Y2IvQ+TIKsE6w+tHqb3K4t50g==",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
